services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  adminer:
    image: dockette/adminer:postgres
    restart: always
    ports:
      - "8888:80"

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    restart: always
    ports:
      - "9090:8080"
    environment:
      # Initial Admin Credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Explicitly set health and metrics if needed, but keeping it minimal
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: 
      - start-dev
      - --db=dev-file

volumes:
  keycloak-data:
    driver: local